In [2]:
import numpy as np

# Expanded Basic Operations

In [4]:
#1.Create a 4x4 matrix with random integers ranging from 10 to 50.
np.random.randint(10,50,(4,4),dtype=int)

array([[42, 31, 48, 27],
       [24, 39, 44, 11],
       [31, 46, 42, 12],
       [11, 36, 36, 47]])

In [6]:
#2.Generate an array of 20 linearly spaced numbers between 0 and 1.
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [7]:
#3.Extract all numbers from an array that are greater than a given threshold (e.g., array > 5).
arr = np.array([[10,34,5,3],
                [50,3,58,4]])
arr[arr>5]

array([10, 34, 50, 58])

In [78]:
#4. Create a checkerboard pattern (8x8 matrix) with alternating 0s and 1s.
arr = np.zeros((8,8),dtype=int)
arr[::2,::2] = 1
arr[1::2,1::2] = 1
print(arr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [25]:
#5. Reverse an array (1D) using slicing.
arr = np.array([9,25,63,2,1,32])
arr[::-1]

array([32,  1,  2, 63, 25,  9])

In [41]:
#6. Find the index of the first occurrence of a value in an array.
arr = np.array([[2, 1, 4, 3],
                [5, 4, 6, 1],
                [2, 7, 8, 10],
                [1, 0, 9, 2]])
print(arr)
n = 9
newarr = np.where(arr == n)
if newarr[0].size>0:
    print(f"The first occurence of the element {n} is found at row {newarr[0][0]} and column {newarr[1][0]}")
else:
    print(f"The element {n} is not found.")

[[ 2  1  4  3]
 [ 5  4  6  1]
 [ 2  7  8 10]
 [ 1  0  9  2]]
The first occurence of the element 9 is found at row 3 and column 2


In [48]:
#7. Create a 1D array of size 10, filled with zeros, and replace the fifth element with 1.
arr=np.zeros(10,dtype=int)
arr[4] = 1
print(arr)

[0 0 0 0 1 0 0 0 0 0]


In [53]:
#8. Create a 2D array of size 3x3 filled with random integers, and flatten it into a 1D array.
arr = np.random.randint(1,31,(3,3))
print(arr,end="\n\n")
print(arr.flatten())

[[15 16 24]
 [23 23 11]
 [ 9 25 10]]

[15 16 24 23 23 11  9 25 10]


In [75]:
#9. Stack two arrays of shape (2, 2) vertically and horizontally.
arr1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr2 = np.array([[11,12,13],
                [14,15,16],
                [17,18,19]])
# print(np.concatenate((a,b),axis=0))
# print(np.concatenate((a,b),axis=1))
print(np.vstack((arr1,arr2)),end="\n\n")
print(np.hstack((arr1,arr2)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [85]:
#10. Find the unique elements in an array and their counts.
arr = np.array([[2, 1, 4, 3],
                [5, 4, 6, 1],
                [2, 7, 8, 10],
                [1, 0, 9, 2]])
data = np.unique(arr,return_counts=True)
print("The unique elements in array : ",data[0])
print("The count of the elements : ",data[1])

The unique elements in array :  [ 0  1  2  3  4  5  6  7  8  9 10]
The count of the elements :  [1 3 3 1 2 1 1 1 1 1 1]
