In [ ]:
import numpy as np

In [5]:
#1.How do you create a 1D array of integers from 0 to 9 using NumPy?
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
#2.How do you create a 3x3 matrix filled with zeros?
arr = np.zeros((3,3),dtype=int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
#3.How can you generate an array of 10 random numbers between 0 and 1?
arr = np.random.rand(10)
print(arr)

[0.49021725 0.51873932 0.1637401  0.04437269 0.12947416 0.14152169
 0.35938811 0.29771978 0.90586235 0.51924324]


In [15]:
#4.How can you reshape a 1D array of 12 elements into a 3x4 2D array?
arr = np.arange(1,13)
print(arr,", size - ",arr.size,", Dimenstion -",str(arr.ndim)+"D")
newarr = arr.reshape(3,4)
print("3X4 2D array : ")
print(newarr)


[ 1  2  3  4  5  6  7  8  9 10 11 12] , size -  12 , Dimenstion - 1D
3X4 2D array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
#5.How do you extract the third column from the following 2D array?
#arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[:,2:3])

[[3]
 [6]
 [9]]


In [23]:
#6.What is the difference between .shape and .size in NumPy?
#.shape relates to the size of the dimensions of an N-dimensional array.
#.size relates to the no.of elements in the array.
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print("Shape : ",np.shape(arr))
print("Size : ",arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape :  (3, 3)
Size :  9


In [29]:
#7.Write a program to find the minimum, maximum, and mean of the array
#arr = np.array([4, 7, 1, 8, 3, 9])
arr = np.array([4, 7, 1, 8, 3, 9])
print(arr)
print("Min : ",arr.min())
print("Maximum : ",arr.max())
print("Mean : ",arr.mean())

[4 7 1 8 3 9]
Min :  1
Maximum :  9
Mean :  5.333333333333333


In [31]:
#8.How can you add 5 to every element of a NumPy array?
arr = np.arange(1,11)
print(arr)
print("After adding 5 to the array : ",arr+5)

[ 1  2  3  4  5  6  7  8  9 10]
After adding 5 to the array :  [ 6  7  8  9 10 11 12 13 14 15]


In [36]:
#9.How do you compute their element-wise sum and dot product?
arr1 = np.array([[1, 3],
              [2, 4]])
arr2 = np.array([[5, 7],
              [6, 8]])
print(arr1,end="\n\n")
print(arr2)
print()
print("Elements-wise sum : ",arr1+arr2)
print("Dot product : ",np.dot(arr1,arr2))


[[1 3]
 [2 4]]

[[5 7]
 [6 8]]

Elements-wise sum :  [[ 6 10]
 [ 8 12]]
Dot product :  [[23 31]
 [34 46]]


In [50]:
#10.How can you replace all negative values in an array with 0?
arr = np.array([1, -2, 3, -4, 5, -6, 7])
print(arr)
#using where
# arr[np.where(arr<0)] = 0
#normal
arr[arr<0] = 0
print("After modification : ",arr)

[ 1 -2  3 -4  5 -6  7]
After modification :  [1 0 3 0 5 0 7]


In [54]:
#11.How can you find the indices of all even numbers in the following array?
#arr = np.array([10, 15, 20, 25, 30])
arr = np.array([10,15,20,25,30])
print(arr)
print(np.where(arr%2==0))

[10 15 20 25 30]
(array([0, 2, 4], dtype=int64),)


In [61]:
#12.Write a program to concatenate two 2D arrays along the rows.
arr1 = np.array([[1, 3],
              [2, 4]])
arr2 = np.array([[5, 7],
              [6, 8]])
print(np.concatenate((arr1,arr2),axis=0))

[[1 3]
 [2 4]
 [5 7]
 [6 8]]


In [68]:
#13.How do you generate a 4x4 matrix of random integers between 1 and 100, and find its transpose?
arr = np.random.randint(1,101,(4,4))
print(arr,end="\n\n")
print("Tanspose : ",end="\n\n")
print(arr.T)
# print(arr.swapaxes(0,1))

[[95  1 71 93]
 [81 91 14 52]
 [48 36 65 82]
 [55 51 11 58]]

Tanspose : 

[[95 81 48 55]
 [ 1 91 36 51]
 [71 14 65 11]
 [93 52 82 58]]


In [89]:
#14.Given a 3x3 array, write a NumPy program to normalize its values so that they range between 0 and 1.
#Normalization formula : (arr-arr.min())/(arr.max()-arr.min())
arr = np.arange(1,10).reshape(3,3)
print(arr,end="\n\n")
print("Normalized array : ")
print((arr-arr.min())/(arr.max()-arr.min()))


[[1 2 3]
 [4 5 6]
 [7 8 9]]

Normalized array : 
[[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


In [91]:
#15.Write a program to filter the values in an array based on a condition (e.g., values greater than 5).
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr[arr>5])

[6 7 8 9]
